INSERT INTO EMPLOYEE ( ID, EMP_DEPARTMENT, EMP_INCOME, EMP_NAME, IS_ACTIVE) VALUES (101, 'IT', 120000.00,'Rock Battle', true);
INSERT INTO EMPLOYEE ( ID, EMP_DEPARTMENT, EMP_INCOME, EMP_NAME, IS_ACTIVE) VALUES (102, 'Marketing', 150000.78,'Mike Miller', false);
INSERT INTO EMPLOYEE ( ID, EMP_DEPARTMENT, EMP_INCOME, EMP_NAME, IS_ACTIVE) VALUES (103, 'Sales', 1898.99,'Sam Smith', true);

INSERT INTO PERSON ( SSN, FIRST_NAME, LAST_NAME, TITLE, AGE, ADDRESS) VALUES (122333444, 'Rock', 'Battle','General', 45,'123 general st');
INSERT INTO PERSON ( SSN, FIRST_NAME, LAST_NAME, TITLE, AGE, ADDRESS) VALUES (122333111, 'Mike', 'Miller','Capitan', 45,'123 Capitan st');
INSERT INTO PERSON ( SSN, FIRST_NAME, LAST_NAME, TITLE, AGE, ADDRESS) VALUES (122333555, 'Sam', 'Smith','Major', 45,'123 Major st');

